// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qorowghrpaerokbmwckj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvcm93Z2hycGFlcm9rYm13Y2tqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDY3MTEsImV4cCI6MjA2ODY4MjcxMX0.8ew3o5Ntm8GbYwBaPKrwbV9Sg6hJksizNgh7Zw9hCqQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});